### ISSUE TITLE
Failed to activate the language-todotxt package

### ISSUE THREAD

**Issue by peterdat** [todotxt/language-todotxt#54]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.0 x64
**Electron**: 2.0.9
**OS**: Microsoft Windows 10 Education
**Thrown From**: [language-todotxt](https://github.com/todotxt/language-todotxt) package 1.1.5

### Stack Trace

Failed to activate the language-todotxt package

```
At letter.toLowerCase is not a function

TypeError: letter.toLowerCase is not a function
    at _loop (/packages/language-todotxt/lib/language-todotxt.js:47:44)
    at Object.activate (/packages/language-todotxt/lib/language-todotxt.js:45:24)
    at Package.activateNow (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:3029631)
    at measure (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:3029043)
    at Package.measure (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:3026674)
    at activationPromise.activationPromise.Promise (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:3028903)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:3028846)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:378471)
    at ~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:912430
    at r (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:907036)
    at o (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:14:1037411)
    at t.bufferStream (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:14:1037565)
    at Socket.e.on (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:14:1036167)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

### Commands

```
     -2:09.0 intentions:highlight (input.hidden-input)
     -2:08.7.0 core:save (input.hidden-input)
     -2:02.4.0 intentions:highlight (input.hidden-input)
     -2:01.2.0 core:undo (input.hidden-input)
  2x -1:58.8.0 core:redo (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.16 
atom-python-run 0.9.7 
atom-python-virtualenv 1.0.2 
autocomplete-java 1.2.7 
autocomplete-python 1.10.12 
busy-signal 1.4.3 
git-control 0.9.0 
git-log 0.4.1 
git-plus 8.1.0 
git-time-machine 2.1.0 
gpp-compiler 3.0.7 
Hydrogen 2.6.0 
ide-java 0.8.3 
ide-python 1.0.0 
intentions 1.1.5 
language-kickstart 0.2.0 
language-puppet 0.23.0 
language-todotxt 1.1.5 
linter 2.2.0 
linter-gcc 0.7.1 
linter-javac 1.9.4 
linter-ui-default 1.7.1 
linter-vagrant-validate 1.1.0 
print-code 0.7.1 
python-debugger 0.2.0 
python-indent 1.1.6 
python-tools 0.6.9 
script 3.18.1 
split-diff 1.5.3 
todo-show 2.3.2 
tree-view-git-status 1.5.2 
vagrant 0.1.0 
```

**Comment by Ryuno-Ki** [comment]
Same on Linux

**Comment by shaneknysh** [comment]
The krzenter PR can be installed manually by cloning that fork to the atom packages folder.

Atom packages is located 
windows 
`%userprofile%\.atom\packages`
linux
`~/.atom/packages`
macOS
I can't find the default location :(

**Comment by shaneknysh** [comment]
The atom package manager is still throwing an error after the merge of this patch. It should have corrected the error but it is still throwing the same error after the merge.

**Comment by karbassi** [comment]
I pushed version 1.2.0 to atom.io

Let me know if that fixes things.

https://atom.io/packages/language-todotxt

**Comment by shaneknysh** [comment]
It's working again!
